stages:
  - stage: SonarQube
    jobs:
      - job: SonarQube
        steps:
          - script: |
              echo Sonarqube checks

  - stage: UnitTests
    jobs:
      - job: UnitTests
        steps:
          - script: |
              echo UnitTests checks

  - stage: DockerBuild
    jobs:
      - job: DockerBuild
        steps:
          - script: |
              docker build -t  ${COMPONENT} .
              

  - stage: DockerPush
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - job: DockerPush
        steps:
          - script: |
              docker login -u akhirr -p Zaqwsx21  
              docker image list 
              docker tag ${COMPONENT} akhirr/${COMPONENT}:${BUILD_SOURCEBRANCHNAME}
              docker image list
              docker push akhirr/${COMPONENT}:${BUILD_SOURCEBRANCHNAME}
